spring:
  datasource:
    url: jdbc:postgresql://localhost:5438/capstone
    username: postgres
    password: capstone
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate



flyway:
  locations: classpath:db/migration